/*
  CamComs ESP32 sender payload.

  Direction:
    ESP32 -> encrypted/encoded HTTP POST -> host

  Fill the configuration block below with values generated by:
    fiona camcoms keygen --device-id host --private-out host.private.json --public-out host.public.json
    fiona camcoms keygen --device-id esp32 --private-out esp32.private.json --public-out esp32.public.json

  The envelope shape matches CamComs.encryption on the Python host.
*/

#include <Arduino.h>
#include <ArduinoJson.h>
#include <HTTPClient.h>
#include <WiFi.h>

// ---------------- Configuration ----------------

static const char *WIFI_SSID = "YOUR_WIFI_SSID";
static const char *WIFI_PASSWORD = "YOUR_WIFI_PASSWORD";

static const char *HOST_URL = "http://192.168.1.10:8080/";

static const char *ESP32_DEVICE_ID = "esp32";
static const char *HOST_DEVICE_ID = "host";

static const char *HOST_ENCRYPTION_PUBLIC_KEY_B64 = "PASTE_HOST_PUBLIC_ENCRYPTION_KEY";
static const char *ESP32_SIGNING_PRIVATE_KEY_B64 = "PASTE_ESP32_PRIVATE_SIGNING_KEY";

static const char *KEY_INFO = "fiona.camcoms.v1";

// ---------------- Encoding Helpers ----------------

String base64UrlEncode(const uint8_t *data, size_t len) {
  static const char table[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
  String out;
  out.reserve(((len + 2) / 3) * 4);

  for (size_t i = 0; i < len; i += 3) {
    uint32_t block = ((uint32_t)data[i]) << 16;
    if (i + 1 < len) block |= ((uint32_t)data[i + 1]) << 8;
    if (i + 2 < len) block |= data[i + 2];

    out += table[(block >> 18) & 0x3f];
    out += table[(block >> 12) & 0x3f];
    out += (i + 1 < len) ? table[(block >> 6) & 0x3f] : '=';
    out += (i + 2 < len) ? table[block & 0x3f] : '=';
  }

  return out;
}

// Python's urlsafe_b64decode accepts padding, so this keeps '=' padding.
String base64UrlEncodeString(const String &text) {
  return base64UrlEncode((const uint8_t *)text.c_str(), text.length());
}

String jsonCanonicalForAad(
  const String &createdAt,
  const String &ephemeralPublicKey,
  const String &messageId,
  const String &messageType,
  const String &nonce,
  const String &recipient,
  const String &salt,
  const String &sender,
  const String &senderSigningPublicKey
) {
  // Matches Python json.dumps(..., sort_keys=True, separators=(",", ":"))
  String json = "{";
  json += "\"created_at\":" + createdAt + ",";
  json += "\"ephemeral_public_key\":\"" + ephemeralPublicKey + "\",";
  json += "\"kind\":\"camcoms.encrypted\",";
  json += "\"message_id\":\"" + messageId + "\",";
  json += "\"message_type\":\"" + messageType + "\",";
  json += "\"nonce\":\"" + nonce + "\",";
  json += "\"recipient\":\"" + recipient + "\",";
  json += "\"salt\":\"" + salt + "\",";
  json += "\"sender\":\"" + sender + "\",";
  json += "\"sender_signing_public_key\":\"" + senderSigningPublicKey + "\",";
  json += "\"version\":1";
  json += "}";
  return json;
}

String jsonCanonicalForSignature(const String &aadJson, const String &ciphertext) {
  String json = aadJson;
  json.remove(json.length() - 1);
  json += ",\"ciphertext\":\"" + ciphertext + "\"}";
  return json;
}

String randomHexId() {
  uint8_t bytes[16];
  fillRandom(bytes, sizeof(bytes));
  char output[33];
  for (size_t i = 0; i < sizeof(bytes); ++i) {
    sprintf(output + (i * 2), "%02x", bytes[i]);
  }
  output[32] = '\0';
  return String(output);
}

// ---------------- Crypto Adapter ----------------
//
// Keep these functions as the only library-specific section. Implement them
// with the ESP32 crypto library you settle on. The Python host expects:
//   X25519 + HKDF-SHA256 + AES-GCM + Ed25519.

void fillRandom(uint8_t *buffer, size_t len) {
  for (size_t i = 0; i < len; ++i) {
    buffer[i] = (uint8_t)esp_random();
  }
}

bool base64UrlDecode32(const char *encoded, uint8_t out[32]) {
  // Replace this with your chosen base64url decoder.
  // Return true only when exactly 32 bytes were decoded into out.
  (void)encoded;
  (void)out;
  return false;
}

bool deriveSenderSigningPublicKey(const char *signingPrivateKeyB64, uint8_t outPublicKey[32]) {
  // Ed25519 public key derivation from private key.
  (void)signingPrivateKeyB64;
  (void)outPublicKey;
  return false;
}

bool generateEphemeralX25519Keypair(uint8_t privateKey[32], uint8_t publicKey[32]) {
  /*
    Required implementation:
      1. Fill privateKey with 32 random bytes.
      2. Clamp it for X25519 if your library does not do that internally.
      3. Derive publicKey from privateKey.
  */
  (void)privateKey;
  (void)publicKey;
  return false;
}

bool encryptForHost(
  const uint8_t *plaintext,
  size_t plaintextLen,
  const uint8_t hostPublicKey[32],
  const uint8_t ephemeralPrivateKey[32],
  const uint8_t *aad,
  size_t aadLen,
  uint8_t salt[16],
  uint8_t nonce[12],
  uint8_t *ciphertextWithTag,
  size_t *ciphertextWithTagLen
) {
  /*
    Required implementation:
      1. X25519(ephemeralPrivateKey, hostPublicKey) -> shared secret.
      2. HKDF-SHA256(shared secret, salt, KEY_INFO) -> 32-byte AES key.
      3. AES-GCM encrypt plaintext with nonce and aad.
      4. Output ciphertext + 16-byte GCM tag in ciphertextWithTag.
  */
  (void)plaintext;
  (void)plaintextLen;
  (void)hostPublicKey;
  (void)ephemeralPrivateKey;
  (void)aad;
  (void)aadLen;
  (void)salt;
  (void)nonce;
  (void)ciphertextWithTag;
  (void)ciphertextWithTagLen;
  return false;
}

bool signEnvelope(
  const uint8_t *canonicalEnvelope,
  size_t canonicalEnvelopeLen,
  const char *esp32SigningPrivateKeyB64,
  uint8_t signature[64]
) {
  // Ed25519 sign(canonical envelope JSON).
  (void)canonicalEnvelope;
  (void)canonicalEnvelopeLen;
  (void)esp32SigningPrivateKeyB64;
  (void)signature;
  return false;
}

// ---------------- Envelope + HTTP ----------------

String buildEncryptedEnvelope(const String &instruction) {
  uint8_t hostPublicKey[32];
  uint8_t senderSigningPublicKey[32];
  uint8_t ephemeralPrivateKey[32];
  uint8_t ephemeralPublicKey[32];
  uint8_t salt[16];
  uint8_t nonce[12];
  uint8_t ciphertextWithTag[512];
  uint8_t signature[64];
  size_t ciphertextWithTagLen = 0;

  if (!base64UrlDecode32(HOST_ENCRYPTION_PUBLIC_KEY_B64, hostPublicKey)) {
    Serial.println("Could not decode host public key.");
    return "";
  }
  if (!deriveSenderSigningPublicKey(ESP32_SIGNING_PRIVATE_KEY_B64, senderSigningPublicKey)) {
    Serial.println("Could not derive ESP32 signing public key.");
    return "";
  }

  fillRandom(salt, sizeof(salt));
  fillRandom(nonce, sizeof(nonce));
  if (!generateEphemeralX25519Keypair(ephemeralPrivateKey, ephemeralPublicKey)) {
    Serial.println("Could not generate ephemeral X25519 keypair.");
    return "";
  }

  String createdAt = String((uint32_t)(millis() / 1000));
  String messageId = randomHexId();
  String senderSigningPublicKeyB64 = base64UrlEncode(senderSigningPublicKey, sizeof(senderSigningPublicKey));
  String ephemeralPublicKeyB64 = base64UrlEncode(ephemeralPublicKey, sizeof(ephemeralPublicKey));
  String saltB64 = base64UrlEncode(salt, sizeof(salt));
  String nonceB64 = base64UrlEncode(nonce, sizeof(nonce));

  String aadJson = jsonCanonicalForAad(
    createdAt,
    ephemeralPublicKeyB64,
    messageId,
    "instruction",
    nonceB64,
    HOST_DEVICE_ID,
    saltB64,
    ESP32_DEVICE_ID,
    senderSigningPublicKeyB64
  );

  if (!encryptForHost(
        (const uint8_t *)instruction.c_str(),
        instruction.length(),
        hostPublicKey,
        ephemeralPrivateKey,
        (const uint8_t *)aadJson.c_str(),
        aadJson.length(),
        salt,
        nonce,
        ciphertextWithTag,
        &ciphertextWithTagLen)) {
    Serial.println("Encryption failed.");
    return "";
  }

  String ciphertextB64 = base64UrlEncode(ciphertextWithTag, ciphertextWithTagLen);
  String canonicalSignedJson = jsonCanonicalForSignature(aadJson, ciphertextB64);

  if (!signEnvelope(
        (const uint8_t *)canonicalSignedJson.c_str(),
        canonicalSignedJson.length(),
        ESP32_SIGNING_PRIVATE_KEY_B64,
        signature)) {
    Serial.println("Signing failed.");
    return "";
  }

  DynamicJsonDocument envelope(2048);
  envelope["version"] = 1;
  envelope["kind"] = "camcoms.encrypted";
  envelope["message_id"] = messageId;
  envelope["message_type"] = "instruction";
  envelope["created_at"] = createdAt.toInt();
  envelope["sender"] = ESP32_DEVICE_ID;
  envelope["recipient"] = HOST_DEVICE_ID;
  envelope["sender_signing_public_key"] = senderSigningPublicKeyB64;
  envelope["ephemeral_public_key"] = ephemeralPublicKeyB64;
  envelope["salt"] = saltB64;
  envelope["nonce"] = nonceB64;
  envelope["ciphertext"] = ciphertextB64;
  envelope["signature"] = base64UrlEncode(signature, sizeof(signature));

  String envelopeJson;
  serializeJson(envelope, envelopeJson);
  return base64UrlEncodeString(envelopeJson);
}

void sendInstructionToHost(const String &instruction) {
  String encodedEnvelope = buildEncryptedEnvelope(instruction);
  if (encodedEnvelope.length() == 0) return;

  HTTPClient http;
  http.begin(HOST_URL);
  http.addHeader("Content-Type", "text/plain; charset=ascii");
  int status = http.POST(encodedEnvelope);
  String response = http.getString();
  http.end();

  Serial.print("Host status: ");
  Serial.println(status);
  Serial.print("Host response: ");
  Serial.println(response);
}

void setup() {
  Serial.begin(115200);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  while (WiFi.status() != WL_CONNECTED) {
    delay(250);
    Serial.print(".");
  }
  Serial.println();
  Serial.print("ESP32 IP: ");
  Serial.println(WiFi.localIP());

  sendInstructionToHost("{\"keys\":[\"alt\",\"s\"],\"type\":\"press\",\"version\":1}");
}

void loop() {
  delay(5000);
}
